{
  "comments": [
    {
      "key": {
        "uuid": "ba3cc151_e2cc7437",
        "filename": "jenkins_jobs/cmd.py",
        "patchSetId": 4
      },
      "lineNbr": 246,
      "author": {
        "id": 6987
      },
      "writtenOn": "2015-06-30T02:06:59Z",
      "side": 1,
      "message": "nit: I guess it could still connect if jenkins is setup with no authentication but wouldn\u0027t it be better to just fail and throw an exception in this case?",
      "revId": "4d44e95db7de4e82d2487f87b9b9b5e6fcfe9e9a",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}