{
  "comments": [
    {
      "key": {
        "uuid": "da86d52c_9df6b85b",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 9,
      "author": {
        "id": 6987
      },
      "writtenOn": "2015-02-05T21:52:43Z",
      "side": 1,
      "message": "Can you please expand on this?  file has been there for a long time and we\u0027ve been testing with python 3.3 and now python 3.4 it seems to work in both cases.",
      "revId": "89cdf59ae5e0d860efd479a3fc563642bf68438a",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}